name: CI (All Apps)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  backend:
    name: Backend
    uses: ./.github/workflows/backend.yml

  frontend:
    name: Frontend
    uses: ./.github/workflows/frontend.yml

  mobile:
    name: Mobile
    uses: ./.github/workflows/mobile.yml

  packages:
    name: Packages
    uses: ./.github/workflows/packages.yml

  landing:
    name: Landing
    uses: ./.github/workflows/landing.yml